name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Flutter Version
        run: flutter --version

      - name: Flutter Doctor
        run: flutter doctor

      - name: Get Packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build IPA
        run: flutter build ipa --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa